############################
## CHANGE THESE
############################

baseURL: 'https://github.com/raulhr16/html-iaw' 
title: 'Rauli'


############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'es'


